### ISSUE TITLE
Sort lines?

### ISSUE THREAD

**Issue by edemaine** [earshinov/vscode-permute-lines#7]
Just discovered this extension via [Syntax.fm](https://www.youtube.com/watch?v=VIdM5VSlJVw). Any chance we could have a "sort lines" feature, similar to the Unix `sort` command? You already have something like `uniq`. 😃

**Comment by earshinov** [comment]
Hey! Wow, having my extension mentioned on the podcast is such a great feeling 🤩 This feature is actually available in VS Code out of the box (unless I misunderstood something), Command Palette > Sort Lines Ascending (the underlying command is `editor.action.sortLinesAscending`). I have it bound to F9 via Keyboard Shortcuts and use it frequently myself.

**Comment by edemaine** [comment]
Ooh, so it is! Thanks!  I guess I still have a lot to learn about VSCode. 😄 
(I guess it could be nice to link to in your README? But not a big deal.)

I can't tell you how many times I've reversed lines manually, but never again. Thank you for your extension!
